### PR TITLE
Add host_msdfs & inherit_acl & hosts allow & hosts deny parameters 

### PR DESCRIPTION
**Pull request by dadez73**
host_msdfs add missing parmeter to enable shares on dfs
inherit_acl  add missing parmeter to enable parent inherited acl

### CODE REVIEW

**Comment by rehanone** [comment]
Thanks for the pull request! Can you please squash your comments and confirm that you have tested these changes?

**Comment by dadez73** [comment]
Hope i understood what you asked. Let me know if further modification are needed.
I tested on our machine and work as expected.

**Comment by rehanone** [comment]
This PR has 7 commits. Can you please squash them in a single commit?

**Comment by dadez73** [comment]
hi, i close this PR.  
I will create a new one from scratch.

**Pull request closed without merging**
