### PR TITLE
Convert from Travis CI to Voxpupuli Github Actions.

### PR DESCRIPTION
**Pull request by bschonec**
Here are [what I think are] the bare minimum changes necessary to migrate off of Travis CI.  I've removed a lot of stuff out of the Gemfile.

The spec tests do run successfully but because I don't know anything about Travis CI and know very little about Github Actions/Voxpupuli workflows I can't guarantee that all of the tests you expect to run are in fact running.

A few things I did:

- Remove Puppet 6 tests
- Added class [parameter documentation](https://github.com/voxpupuli/puppet-lint-param-docs) just to quiet down the checker.  That'll have to be addressed in another pull request.
- Commented out some disabled test in the Rakefile
- Fixed spacing/linting issues in manifests

No changes from other pull requests are included in this pull request.

### CODE REVIEW

**Comment by rehanone** [comment]
Well I guess we should start with this PR and see what needs to be fixed after the GHA pipeline is working. Please let me know if this is ready and I will merge it. Thanks a lot once again for this amazing effort!

**Comment by bschonec** [comment]
I think it's ready for merging albeit with a possibility of some tests no longer being performed.  Again, my inexperience with Travis and CI/CD in general causes me to make that statement.

If you do merge it, then I can modify #37 so that it runs and tests properly.

**Comment by rehanone** [comment]
I had to make a little change for the actions trigger but it looks like the tests are working, at least the unit test. Not sure about the integration tests though. Looks like they might be missing.

**Comment by bschonec** [comment]
Probably.  I'm just starting my journey here.  Can you point me to where the integrations tests USED TO be?  I assume in the .travis-ci.yaml file but if you can confirm where they were located I'll try to move them, too.

**Comment by rehanone** [comment]
All Integration tests are in /spec/acceptance/class_spec.rb. They dont have much coverage but they used to run /examples/init.pp file on various OS docker images. This was helpful to spot any changes happening in new OS releases.

**Pull request merged**
