### PR TITLE
Adding obey pam restrictions param

### PR DESCRIPTION
**Pull request by welchnut**

### CODE REVIEW

**Comment by welchnut** [comment]
@rehanone it looks like this test is failing due to an expired key fro Debian 8 (Line 838 of the failed test). How should I proceed?

**Comment by rehanone** [comment]
Yes I think debian 8 I think is gone out of service. I will remove it.

**Comment by rehanone** [comment]
@welchnut , removed the debian 8 from tests. Can you please rebase now.

**Comment by welchnut** [comment]
I merged the changes in upstream/master into this branch. I can't squash the commits because one of them is a merge commit.

**Pull request merged**
