### PR TITLE
Add inherit options

### PR DESCRIPTION
**Pull request by casey36901**
Adds inherit owner and inherit permissions share options.

### CODE REVIEW

**Review by rehanone — CHANGES_REQUESTED** [review]
Thanks for creating the pr. can you please squash your commits on this pr please?

**Comment by rehanone** [comment]
It looks like one of the tests is failing:

     Failure/Error: is_expected.to have_samba__option_resource_count(56)

       expected that the catalogue would contain exactly 56 Samba::Option resources but it contains 58`
`

It is inside file [spec/share_spec.rb line 46](https://github.com/rehanone/puppet-samba/blob/master/spec/defines/share_spec.rb#L46).

Hope that helps.

**Comment by casey36901** [comment]
@rehanone I modified the test so it is working as expected now. Would you like me to squash into one commit again before merging?

**Comment by rehanone** [comment]
Yes please 😊

**Comment by casey36901** [comment]
@rehanone Should be good to go now!

**Comment by rehanone** [comment]
Looks good!

**Pull request merged**
